---
title: "HW 3b: Penguin taxidermy"
author: "MSCI 599"
date: "12/30/2020"
output: html_document
---

***

```{r setup, include=FALSE}
# Put any RMarkdown options you'd like to have throughout the document here
# These are the options I like to use to make figures smaller and print code output right below the command:
knitr::opts_chunk$set(fig.width=6, fig.asp = 0.618, collapse=TRUE) 
```

#### Unit 3: Penguins

#### Homework # 3b penguin taxidermy

#### Skill practice: data exploration, statistical diagnostics, linear models

***

Imagine that you are planning a research project with a museum's collection of taxedermied penguins. You can easily measure bill length, bill depth and flipper length on each stuffed bird. You can also identify the sex of the stuffed bird, and you have notes that indicate the year and island that the bird was collected. However, for the work you are interested in doing, it's really important that you know each individual's body mass, or at least can estimate it reasonably well. However, weighing your taxidermied penguin doesn't really tell you anything about the animal's weight before it was killed and eviscerated... so you're in trouble. 

Luckily, another lab group did a penguin field study of the same three penguin species and made it publicly available as the `palmerpenguins` library in R. This data has observations on the same islands and during the same years that your (killed and stuffed) birds were collected. Even better, the `palmerpenguins` data is available online as an R package! Build the best model(s) that you can using the `palmerpenguins` data to predict penguin body mass. Make sure you conduct some exploratory data analysis, and run diagnostics on the models that you build. Explain why you picked the model(s) that you did, and plot the predictions and standard errors or confidence intervals of the model, along with the `palmerpenguins` data you used to generate it. 

Finally, read in the `.csv` file with the measurements of your 3 taxidermied penguins, affectionately named MrPopper, Tacky and Hubie. Use your model to estimate the body mass of these 3 stuffed birds and report these estimates. 

Turn in your homework in a well-organized R Markdown file.




